--1
CREATE DATABASE BookOnline
ON PRIMARY (NAME='Book_dat',FILENAME='C:\DATA\BookOnline.mdf',SIZE=5MB, MAXSIZE=unlimited, FILEGROWTH=15%)
LOG ON (NAME='Book_log',FILENAME='C:\DATA\BookOnline.ldf',SIZE=2MB, MAXSIZE=10MB, FILEGROWTH=1MB)
GO

--2
CREATE DATABASE SaleOnline
ON PRIMARY 
(NAME='Sales_dat',FILENAME='C:\DATA\SaleOnline.mbf',
SIZE=5MB,MAXSIZE=unlimited,FILEGROWTH=15%),
FILEGROUP SalesGroup
(NAME='Sales2_dat',FILENAME='C:\DATA\SaleOnline.ndf',
SIZE=5MB,MAXSIZE=20MB,FILEGROWTH=5MB),
(NAME='Sales3_dat',FILENAME='C:\DATA\SaleOnline.tdf',
SIZE=5MB,MAXSIZE=20MB,FILEGROWTH=5MB)
LOG ON (NAME='Sales_log',FILENAME='C:\DATA\SaleOnline.ldf',
SIZE=2MB,MAXSIZE=100MB,FILEGROWTH=10%)
GO

--3
CREATE DATABASE UntiedAir
ON PRIMARY 
(NAME='UnitedAir1_dat',FILENAME='C:\DATA\UntiedAir1.mbf',
SIZE=5MB,MAXSIZE=10MB,FILEGROWTH=15%),
(NAME='UnitedAir2_dat',FILENAME='C:\DATA\UntiedAir2.mbf',
SIZE=5MB,MAXSIZE=10MB,FILEGROWTH=15%),
FILEGROUP UntitedAirGroup1
(NAME='UnitedAirGrp1F1',FILENAME='C:\DATA\UntitedAirGroup1.ndf',
SIZE=5MB,MAXSIZE=20MB,FILEGROWTH=5MB),
(NAME='UnitedAirGrp1F2',FILENAME='C:\DATA\UntitedAirGroup1.tdf',
SIZE=5MB,MAXSIZE=20MB,FILEGROWTH=5MB),
FILEGROUP UntitedAirGroup2
(NAME='UnitedAirGrp2F1',FILENAME='C:\DATA\UntitedAirGroup2.ndf',
SIZE=5MB,MAXSIZE=20MB,FILEGROWTH=5MB),
(NAME='UnitedAirGrp2F2',FILENAME='C:\DATA\UntitedAirGroup2.tdf',
SIZE=5MB,MAXSIZE=20MB,FILEGROWTH=5MB)
GO

--4 
ALTER DATABASE BookOnline
MODIFY NAME= LibraryDB
GO
--5 
DROP DATABASE LibraryDB 
DROP DATABASE UntiedAir
DROP DATABASE SaleOnline
GO