CREATE DATABASE StudentDB
ON PRIMARY 
(NAME='Student_dat',FILENAME='C:\DATA\StudentDB.mdf',
SIZE=5MB,MAXSIZE=unlimited,FILEGROWTH=10%)
LOG ON (NAME='Student_log',FILENAME='C:\DATA\StudentDB.ldf',
SIZE=2MB,MAXSIZE=15MB,FILEGROWTH=1MB)
GO

CREATE TABLE tbStudents(
	Roll_no INT 
)